services:
    redis:
        image: redis:latest
        container_name: redis_server
        restart: always
        ports:
            - "6379:6379"
        volumes:
            # Mounts a local directory for data persistence
            - ./redis_data:/data
        command: redis-server --appendonly yes --requirepass 123
volumes:
    redis_data:
